# Cross-compilation configuration for probe
# This configures the cross tool for ARM64 Linux builds

[build.env]
passthrough = [
    "CARGO_INCREMENTAL",
    "CARGO_TERM_COLOR",
]

[target.aarch64-unknown-linux-gnu]
# Use vendored OpenSSL to avoid system dependency conflicts
pre-build = [
    "dpkg --add-architecture arm64",
    "apt-get update",
    "apt-get install --assume-yes libssl-dev:arm64 pkg-config"
]

[target.aarch64-unknown-linux-gnu.env]
# Configure OpenSSL for cross-compilation
OPENSSL_STATIC = "1"
OPENSSL_LIB_DIR = "/usr/lib/aarch64-linux-gnu"
OPENSSL_INCLUDE_DIR = "/usr/include/openssl"
PKG_CONFIG_ALLOW_CROSS = "1"
PKG_CONFIG_PATH = "/usr/lib/aarch64-linux-gnu/pkgconfig"