name: Visor Code Review

on:
  pull_request:
    types: [opened, synchronize]
  issues:
    types: [opened]
  issue_comment:
    types: [created]

permissions:
  contents: read
  pull-requests: write
  issues: write
  checks: write

jobs:
  code-review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - uses: probelabs/visor@main
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}
          installation-id: ${{ secrets.APP_INSTALLATION_ID }}
          debug: 'true'
        env:
          # AI Provider API Keys (configure one of these in your repository secrets)
          # GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
          ANTHROPIC_AUTH_TOKEN: ${{ secrets.GLM_API_KEY }}
          ANTHROPIC_BASE_URL: 'https://api.z.ai/api/anthropic/v1'
          # OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          # Optional: Specify the AI model to use
          MODEL_NAME: 'glm-4.6'
